// This file renders the reproducible Runtime workstream index and inspection data.
package engine

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// issueRecord contains only the fields needed by INDEX.md.
type issueRecord struct {
	Name   string
	Status string
	Title  string
}

// workRecord is the engine's filesystem-derived view of one Work.
type workRecord struct {
	Slug      string
	State     string
	Path      string
	PRD       FrontMatter
	PRDExists bool
	HANDOFF   string
	Issues    []issueRecord
}

// listWorks reads active and completed Work directories in deterministic order.
func (e *Engine) listWorks() ([]workRecord, error) {
	var records []workRecord
	for _, state := range []string{"active", "completed"} {
		root := e.path(e.Profile.ActiveRoot)
		if state == "completed" {
			root = e.path(e.Profile.CompletedRoot)
		}
		entries, err := os.ReadDir(root)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return nil, fmt.Errorf("read %s Works: %w", state, err)
		}
		for _, entry := range entries {
			if !entry.IsDir() {
				continue
			}
			record, err := e.readWorkRecord(filepath.Join(root, entry.Name()), entry.Name(), state)
			if err != nil {
				return nil, err
			}
			records = append(records, record)
		}
	}
	sort.Slice(records, func(i, j int) bool {
		if records[i].State != records[j].State {
			return records[i].State < records[j].State
		}
		return records[i].Slug < records[j].Slug
	})
	return records, nil
}

// readWorkRecord reads PRD and Issue metadata without rejecting malformed content.
func (e *Engine) readWorkRecord(path, slug, state string) (workRecord, error) {
	record := workRecord{
		Slug:    slug,
		State:   state,
		Path:    path,
		HANDOFF: filepath.Join(path, "HANDOFF.md"),
	}
	prdPath := filepath.Join(path, "PRD.md")
	if data, err := os.ReadFile(prdPath); err == nil {
		record.PRDExists = true
		if front, parseErr := parseFrontMatter(data); parseErr == nil {
			record.PRD = front
		}
	} else if !os.IsNotExist(err) {
		return record, fmt.Errorf("read %s: %w", e.relativePath(prdPath), err)
	}
	issuesPath := filepath.Join(path, "issues")
	entries, err := os.ReadDir(issuesPath)
	if os.IsNotExist(err) {
		return record, nil
	}
	if err != nil {
		return record, fmt.Errorf("read %s: %w", e.relativePath(issuesPath), err)
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		issue := issueRecord{Name: entry.Name(), Status: "unknown", Title: entry.Name()}
		data, readErr := os.ReadFile(filepath.Join(issuesPath, entry.Name()))
		if readErr == nil {
			if front, parseErr := parseFrontMatter(data); parseErr == nil {
				if front.Status != "" {
					issue.Status = front.Status
				}
				if front.Title != "" {
					issue.Title = front.Title
				}
			}
		} else if !os.IsNotExist(readErr) {
			return record, fmt.Errorf("read %s: %w", e.relativePath(filepath.Join(issuesPath, entry.Name())), readErr)
		}
		record.Issues = append(record.Issues, issue)
	}
	sort.Slice(record.Issues, func(i, j int) bool { return record.Issues[i].Name < record.Issues[j].Name })
	return record, nil
}

// renderIndex builds the complete generated index from repository state.
func (e *Engine) renderIndex() ([]byte, error) {
	records, err := e.listWorks()
	if err != nil {
		return nil, err
	}
	var builder strings.Builder
	builder.WriteString("# Runtime Index\n\n")
	builder.WriteString("> Generated by Documentation Engine. Do not edit manually.\n\n")
	for _, state := range []string{"active", "completed"} {
		title := "Active Works"
		if state == "completed" {
			title = "Completed Works"
		}
		builder.WriteString("## " + title + "\n\n")
		found := false
		for _, record := range records {
			if record.State != state {
				continue
			}
			found = true
			builder.WriteString("### " + record.Slug + "\n\n")
			builder.WriteString("- PRD: `" + e.relativePath(filepath.Join(record.Path, "PRD.md")) + "`\n")
			builder.WriteString("- HANDOFF: `" + e.relativePath(record.HANDOFF) + "`\n")
			if state == "completed" {
				outcome := record.PRD.Outcome
				if outcome == "" {
					outcome = "unknown"
				}
				builder.WriteString("- Outcome: " + outcome + "\n")
			}
			builder.WriteString("- Issues:\n")
			if len(record.Issues) == 0 {
				builder.WriteString("  - (none)\n")
			} else {
				for _, issue := range record.Issues {
					builder.WriteString("  - " + issue.Name + " [" + issue.Status + "] " + issue.Title + "\n")
				}
			}
			builder.WriteString("\n")
		}
		if !found {
			builder.WriteString("- None\n\n")
		}
	}
	return []byte(builder.String()), nil
}

// GenerateIndex regenerates .scratch/INDEX.md from active and completed Works.
func (e *Engine) GenerateIndex() (IndexResult, error) {
	data, err := e.renderIndex()
	if err != nil {
		return IndexResult{}, err
	}
	path := e.path(e.Profile.IndexPath)
	previous, existed, err := readOptional(path)
	if err != nil {
		return IndexResult{}, fmt.Errorf("read existing INDEX: %w", err)
	}
	if err := writeAtomic(path, data, 0o644); err != nil {
		return IndexResult{}, err
	}
	return IndexResult{Path: e.relativePath(path), Changed: !existed || string(previous) != string(data)}, nil
}

// Synchronize refreshes generated metadata and records an explicit no-change Knowledge result.
func (e *Engine) Synchronize() (SyncResult, error) {
	index, err := e.GenerateIndex()
	if err != nil {
		return SyncResult{}, err
	}
	return SyncResult{NoKnowledgeChange: true, Index: index}, nil
}

// Inspect returns a repository summary without modifying repository state.
func (e *Engine) Inspect() (InspectReport, error) {
	records, err := e.listWorks()
	if err != nil {
		return InspectReport{}, err
	}
	summaries := make([]WorkSummary, 0, len(records))
	for _, record := range records {
		summary := WorkSummary{
			Slug:        record.Slug,
			State:       record.State,
			PRDPath:     e.relativePath(filepath.Join(record.Path, "PRD.md")),
			HANDOFFPath: e.relativePath(record.HANDOFF),
			IssueCount:  len(record.Issues),
			Outcome:     record.PRD.Outcome,
		}
		summaries = append(summaries, summary)
	}
	knowledgeCount, err := e.countKnowledgeDocuments()
	if err != nil {
		return InspectReport{}, err
	}
	return InspectReport{
		SpecificationVersion: SpecificationVersion,
		EngineVersion:        EngineVersion,
		RepositoryProfile:    e.Profile.Name,
		Root:                 e.Root,
		KnowledgeDocuments:   knowledgeCount,
		ActiveWorks:          countState(records, "active"),
		CompletedWorks:       countState(records, "completed"),
		Works:                summaries,
	}, nil
}

// countState counts Works in one observable lifecycle state.
func countState(records []workRecord, state string) int {
	count := 0
	for _, record := range records {
		if record.State == state {
			count++
		}
	}
	return count
}

// countKnowledgeDocuments counts Markdown Knowledge artifacts in the three categories.
func (e *Engine) countKnowledgeDocuments() (int, error) {
	count := 0
	for _, category := range e.Profile.KnowledgeEntries {
		root := e.path(category.Directory)
		if _, err := os.Stat(root); os.IsNotExist(err) {
			continue
		}
		err := filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if !entry.IsDir() && strings.EqualFold(filepath.Ext(entry.Name()), ".md") && entry.Name() != "AGENTS.md" && entry.Name() != "CLAUDE.md" {
				count++
			}
			return nil
		})
		if err != nil {
			return 0, err
		}
	}
	return count, nil
}
