// This file initializes the normative Single Repository Profile structure.
package engine

import (
	"bytes"
	"fmt"
	"os"
)

const defaultAgentEntry = `# Documentation OS Agent Entry

Documentation OS Specification: 1.0
Repository Profile: Single Repository

Persistent Knowledge is stored in docs/.
Runtime Workspaces are stored in .scratch/active/ and .scratch/completed/.
Use the Documentation Engine for validation, synchronization, Work generation, and completion.
`

const defaultScratchEntry = `# Documentation OS Runtime Entry

Runtime Workspaces live under active/ and completed/.
Core Runtime Assets are PRD.md, issues/, and HANDOFF.md.
INDEX.md is generated by the Documentation Engine.
`

// Initialize creates the required Single Repository Profile directories and entry points.
func (e *Engine) Initialize() error {
	directories := []string{
		e.Profile.KnowledgeRoot,
		e.Profile.ArchitectureDir,
		e.Profile.ADRDir,
		e.Profile.StandardsDir,
		e.Profile.InboxDir,
		e.Profile.RuntimeRoot,
		e.Profile.ActiveRoot,
		e.Profile.CompletedRoot,
	}
	for _, relative := range directories {
		if err := os.MkdirAll(e.path(relative), 0o755); err != nil {
			return fmt.Errorf("initialize %s: %w", relative, err)
		}
	}
	if err := e.ensureMirror(e.Profile.RootAgents, e.Profile.RootClaude, []byte(defaultAgentEntry)); err != nil {
		return err
	}
	if err := e.ensureMirror(e.Profile.ScratchAgents, e.Profile.ScratchClaude, []byte(defaultScratchEntry)); err != nil {
		return err
	}
	if _, err := e.GenerateIndex(); err != nil {
		return fmt.Errorf("initialize generated INDEX: %w", err)
	}
	return nil
}

// ensureMirror creates or verifies a canonical Agent Entry and its mirror.
func (e *Engine) ensureMirror(canonicalRelative, mirrorRelative string, defaultContent []byte) error {
	canonicalPath := e.path(canonicalRelative)
	mirrorPath := e.path(mirrorRelative)
	canonical, canonicalExists, err := readOptional(canonicalPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", canonicalRelative, err)
	}
	mirror, mirrorExists, err := readOptional(mirrorPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", mirrorRelative, err)
	}
	if canonicalExists && mirrorExists {
		if !bytes.Equal(canonical, mirror) {
			return fmt.Errorf("%w: %s and %s are not content-equivalent", ErrInvalidRepository, canonicalRelative, mirrorRelative)
		}
		return nil
	}
	canonicalMissing := !canonicalExists
	if canonicalMissing {
		if mirrorExists {
			canonical = mirror
		} else {
			canonical = defaultContent
		}
		if err := writeAtomic(canonicalPath, canonical, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", canonicalRelative, err)
		}
	}
	if !mirrorExists || canonicalMissing || !bytes.Equal(canonical, mirror) {
		if err := writeAtomic(mirrorPath, canonical, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", mirrorRelative, err)
		}
	}
	return nil
}
